export const animals = [
  "airbaloon.svg",
  "android.svg",
  "arcade.svg",
  "basket.svg",
  "bean.svg",
  "bee.svg",
  "boat.svg",
  "bones.svg",
  "chat.svg",
  "christian-love.svg",
  "clap.svg",
  "cop-male.svg",
  "cucumber.svg",
  "facebook.svg",
  "family-institution.svg",
  "fear.svg",
  "flag.svg",
  "gift.svg",
  "grave.svg",
  "heart-hand.svg",
  "knight.svg",
  "link.svg",
  "macpro.svg",
  "minion-batman.svg",
  "mirror.svg",
  "mobile.svg",
  "monkey-silent.svg",
  "octopus-angry.svg",
  "parka.svg",
  "pig.svg",
  "planets.svg",
  "pluger.svg",
  "polygon.svg",
  "potion.svg",
  "Predator.svg",
  "puzzle.svg",
  "search.svg",
  "shit-sunglasses.svg",
  "short-hair.svg",
  "spray.svg",
  "student-female.svg",
  "sun.svg",
  "topview.svg",
  "troller.svg",
  "twitter.svg",
  "umbrella-rain.svg",
  "vault.svg",
  "vision-jew.svg",
  "Walle-female.svg",
  "water-bottle.svg",
];
const images = [
  { id: 1, src: `SVG/${animals[0]}`, title: "foo", description: "bar" },
  //   { id: 2, src: "./assets/image02.jpg", title: "foo", description: "bar" },
  //   { id: 3, src: "./assets/image03.jpg", title: "foo", description: "bar" },
  //   { id: 4, src: "./assets/image04.jpg", title: "foo", description: "bar" },
  //   { id: 5, src: "./assets/image05.jpg", title: "foo", description: "bar" },
  //   ...etc,
];

function imageLoader() {
  return images;
}

export default imageLoader;
