/*global chrome*/
import React, { Component } from "react";
import M from "materialize-css";
import { withRouter } from "react-router-dom";
import "./materialize.min.css";
import "./CreateJoinTeam.css";

class CreateJoinTeam extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  componentDidMount = () => {
    M.AutoInit();
    // this.getEmail(this.setHeaderEmail);
    this.setupButtonListener();
  };
  /**
   * Get the email from background page and update the html
   * @author : Karl Wang
   * @param {function} setEmailCallback Send the email to the html
   */
  getEmail = (setEmailCallback) => {
    // the message to be sent
    let msg = { for: "background", message: "get email" };
    chrome.runtime.sendMessage(msg, function (response) {
      // set the email on html
      setEmailCallback(response.email);
    });
  };
  /**
   * Get the prefix of the email and show it on html
   * @author : Karl Wang
   * @param {string} email The email to be shown on html
   */
  setHeaderEmail = (email) => {
    let insertEmail = document.querySelector("#insertEmail");
    insertEmail.textContent = email.substr(0, email.indexOf("@"));
  };

  // function setTeamCode(teamCode) {
  //   let code = document.querySelector("#autogeneratedTeamCode");
  //   code.value = teamCode;
  // }
  // function getTeamCode() {
  //   return new Promise(function (resolve, reject) {
  //     let msg = { for: "background", message: "get team code" };
  //     chrome.runtime.sendMessage(msg, function (response) {
  //       resolve(response.teamCode);
  //     });
  //   });
  // }
  /**
   * Setup the listener for create team and join team button
   * @author : Karl Wang
   */
  setupButtonListener = () => {
    let createButton = document.querySelector("#createButton");
    createButton.addEventListener("click", this.onCreateTeam);
    // createButton.addEventListener("click", function(){
    //     console.log("clicked")
    // });
    let joinButton = document.querySelector("#joinButton");
    joinButton.addEventListener("click", this.onJoinTeam);
  };

  /**
   * Send the team name to background, which handles create team on database
   * Do preliminary checking if the team name is legit
   * @author : Karl Wang
   */
  onCreateTeam = () => {
    let teamName = document.querySelector("#teamName").value;
    //   team name is empty
    if (teamName === "") {
      M.toast({ html: "Team name cannot be empty!", displayLength: 2000 });
      return;
    }
    let msg = {
      for: "background",
      message: "create team",
      teamName: teamName,
    };
    let that = this;
    //   send to background page
    chrome.runtime.sendMessage(msg, (response) => {
      console.log(response);
      chrome.storage.local.set({ prevTeam: response });
      that.props.history.push("/");
    });
  };
  /**
   * Send the request along with the team code to background page
   * Do preliminary checking to see if the team code is valid
   * @author : Karl Wang
   */
  onJoinTeam = () => {
    let teamCode = document.querySelector("#teamCode").value;
    if (teamCode.length != 5) {
      M.toast({
        html: "Team code should be 5 characters!",
        displayLength: 2000,
      });
      return;
    }
    //   check if it only contains alphabets and numbers
    const regex = /^[A-Z0-9]+$/i;
    if (!regex.test(teamCode)) {
      M.toast({
        html: "Team code should only contains alphabets and numbers",
        displayLength: 2000,
      });
      return;
    }

    let msg = {
      for: "background",
      message: "join team",
      teamCode: teamCode.toUpperCase(),
    };
    chrome.runtime.sendMessage(msg, (response) => {
      if (response === "team code not found") {
        M.toast({
          html: "Team code does not exist!",
          displayLength: 2000,
        });
        return;
      } else if (response === "success") {
        chrome.storage.local.set({
          prevTeam: teamCode,
        });
        this.props.history.push("/");
        return;
      } else if (response === "already joined the group") {
        M.toast({
          html: "You have already joined this group",
          displayLength: 2000,
        });
        return;
      }
    });
  };

  render() {
    return (
      <div>
        {/* <div className="center-align">
          <h4 className="blue-grey-text text-lighten-1">
            Hello, <span id="insertEmail"></span>
          </h4>
        </div> */}

        <div className="row">
          <div className="col s12">
            {/* <div className="divider col s12"></div> */}
            <ul className="tabs">
              <li className="tab col s6">
                {/* <!-- First Tab --> */}
                <a className="active" href="#createTeam">
                  Create Team
                </a>
              </li>
              <li className="tab col s6">
                {/* <!-- Second Tab --> */}
                <a className="active" href="#joinTeam">
                  Join Team
                </a>
              </li>
            </ul>
          </div>
          <div id="createTeam" className="col s12">
            {/* <!-- Target of first tab -->
        <!-- Row for Team Name --> */}
            <div className="row">
              <div className="input-field col s12">
                <input id="teamName" type="text" className="validate" />
                <label for="teamName">Team Name</label>
              </div>
            </div>
            {/* <!-- Row for CREATE --> */}
            <div className="row center-align">
              <div className="col s12">
                <button
                  id="createButton"
                  className="waves-effect waves-light btn-large red accent-1"
                >
                  Create
                </button>
              </div>
            </div>
          </div>

          {/* <!-- Target for the second tab --> */}
          <div id="joinTeam" className="col s12">
            {/* <!-- second tab input team code --> */}
            <div className="row">
              <div className="input-field col s12">
                <input
                  maxlength="5"
                  id="teamCode"
                  type="text"
                  className="validate"
                />
                <label for="teamCode">Team Code</label>
              </div>
            </div>

            {/* <!-- Row for JOIN --> */}
            <div className="row center-align">
              <div className="col s12">
                <button
                  id="joinButton"
                  className="waves-effect waves-light btn-large red accent-1"
                >
                  Join
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
export default withRouter(CreateJoinTeam);
